spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Execute SQL scripts
spring.sql.init.mode=always

# Run data.sql after Hibernate (if using Hibernate DDL)
spring.jpa.defer-datasource-initialization=true