spring:
  application:
    name: scientific-journal-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/scientific_journal
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  sync:
    cron: "0 0 2 * * *"
